@startuml

title __EINKAUFSLISTE's Class Diagram__\n

  namespace com.example.einkaufsliste {
    interface com.example.einkaufsliste.ChangeFragmentInterface {
        {abstract} + changeFragment()
        {abstract} + setLoginItemText()
        {abstract} + setUsernameText()
    }
  }
  

  namespace com.example.einkaufsliste {

    class com.example.einkaufsliste.MainActivity {
        - mAppBarConfiguration : AppBarConfiguration
        - navigationView : NavigationView
        - tvUsername : TextView
        + changeFragment()
        + onCreateOptionsMenu()
        + onSupportNavigateUp()
        + setLoginItemText()
        + setUsernameText()
        # onCreate()
        - startThreadForUpdatingTheUser()
    }
  }
  

  namespace com.example.einkaufsliste {
    class com.example.einkaufsliste.Repository {
        {static} + INVALID_PASSWORD : int
        {static} + INVALID_USER : int
        {static} + LOGIN_SUCCEED : int
        {static} + REGISTER_SUCCEED : int
        {static} + USER_ALREADY_EXIST : int
        - currentBuyingListId : int
        {static} - instance : Repository
        - ipAddress : String
        - runPollingThread : Boolean
        + getCurrentBuyingListId()
        {static} + getInstance()
        + getIpAddress()
        + getRunPollingThread()
        + getUnitList()
        + getUser()
        + setCurrentBuyingListId()
        + setIpAddress()
        + setRunPollingThread()
        + setUser()
        - Repository()
    }
    namespace models {
          class com.example.einkaufsliste.models.BuyingList {
              - allArticles : Collection<Article>
              - buyingDate : Date
              - creationDate : Date
              - id : int
              - name : String
              {static} - serialVersionUID : long
              + BuyingList()
              + BuyingList()
              + BuyingList()
              + BuyingList()
              + getAllArticles()
              + getBuyingDate()
              + getCreationDate()
              + getDate()
              + getId()
              + getName()
              + setAllArticles()
              + setBuyingDate()
              + setCreationDate()
              + setDate()
              + setId()
              + setName()
              + toString()
              - getCurrentDate()
          }
        }

         class com.example.einkaufsliste.models.User {
                   - allBuyingLists : Collection<BuyingList>
                   - id : long
                   - name : String
                   - password : String
                   {static} - serialVersionUID : long
                   + User()
                   + User()
                   + getBuyingLists()
                   + getId()
                   + getName()
                   + getPassword()
                   + setBuyingLists()
                   + setId()
                   + setName()
                   + setPassword()
                   + toString()
          }
          class com.example.einkaufsliste.models.Article {
                      - amount : long
                      - id : long
                      - name : String
                      {static} - serialVersionUID : long
                      - unit : String
                      + Article()
                      + getAmount()
                      + getBuyingList()
                      + getId()
                      + getName()
                      + getUnit()
                      + setAmount()
                      + setBuyingList()
                      + setId()
                      + setName()
                      + setUnit()
           }
           namespace rest {
                 class com.example.einkaufsliste.rest.InfrastructureWebservice {
                     - URL : String
                     - client : OkHttpClient
                     - connection : URLConnection
                     - gson : Gson
                     - httpConnection : HttpURLConnection
                     - url : URL
                     - urlString : String
                     + addArticle()
                     + addBuyingList()
                     + addUserToBuyingList()
                     + deleteArticle()
                     + deleteBuyingList()
                     + getBuyingList()
                     + login()
                     + register()
                 }
               }
  }

  namespace com.example.einkaufsliste {
      namespace ui.lists {
        class com.example.einkaufsliste.ui.lists.BuyingListsAdapter {
            - buyingLists : List<BuyingList>
            + BuyingListsAdapter()
            + getItemCount()
            + onBindViewHolder()
            + onCreateViewHolder()
            + setBuyingLists()
        }
      }
    }


    namespace com.example.einkaufsliste {
      namespace ui.lists {
        class com.example.einkaufsliste.ui.lists.BuyingListsAdapter.BuyingListHolder {
            - button : Button
            - layout : View
            + BuyingListHolder()
            + add()
            + remove()
        }
      }
    }


    namespace com.example.einkaufsliste {
      namespace ui.lists {
        class com.example.einkaufsliste.ui.lists.ListDataAdapter {
            - liste : List<ListData>
            + ListDataAdapter()
            + getItemCount()
            + onBindViewHolder()
            + onCreateViewHolder()
        }
      }
    }


    namespace com.example.einkaufsliste {
      namespace ui.lists {
        class com.example.einkaufsliste.ui.lists.ListDataAdapter.FirstViewHolder {
            - button : Button
            - editText : EditText
            - layout : View
            - textView : TextView
            + FirstViewHolder()
            + add()
            + remove()
        }
      }
    }


    namespace com.example.einkaufsliste {
      namespace ui.lists {
        class com.example.einkaufsliste.ui.lists.ListDataFragment {
            - btnAddUser : Button
            - content : List<ListData>
            - edit_text_ListData : EditText
            - fab1 : FloatingActionButton
            - recyclerView : RecyclerView
            - spinner : Spinner
            - tvAddUser : TextView
            + onCreateView()
            - inflatelistDataListDialog()
            - initRecyclerView()
        }
      }
    }


    namespace com.example.einkaufsliste {
      namespace ui.lists {
        class com.example.einkaufsliste.ui.lists.ListDataViewModel {
            - ListData : List<ListData>
            + ListDataViewModel()
            + addUser()
            + getListData()
        }
      }
    }


    namespace com.example.einkaufsliste {
      namespace ui.lists {
        class com.example.einkaufsliste.ui.lists.ListsFragment {
            - builder : Builder
            - floatingActionButton : FloatingActionButton
            - recyclerView : RecyclerView
            + onCreateView()
            - inflateAddBuyingListDialog()
            - initRecyclerView()
            - preapareAndBuildDialog()
        }
      }
    }


    namespace com.example.einkaufsliste {
      namespace ui.lists {
        class com.example.einkaufsliste.ui.lists.ListsViewModel {
            - allbuyingLists : MutableLiveData<Collection<BuyingList>>
            + ListsViewModel()
            + addOneBuyingList()
            + getAllbuyingLists()
            {static} + getDateFromDatePicker()
            + removeBuyingList()
            + setAllbuyingLists()
        }
      }
    }

    namespace com.example.einkaufsliste {
        namespace ui.login {
          class com.example.einkaufsliste.ui.login.LoginFragment {
              - btnLogin : Button
              - btnLogout : Button
              - btnRegister : Button
              - etPassword : EditText
              - etUser : EditText
              - layoutLogin : ConstraintLayout
              - layoutLogout : ConstraintLayout
              - tvLogout : TextView
              - tvResult : TextView
              + onCreateView()
          }
        }
      }


      namespace com.example.einkaufsliste {
        namespace ui.login {
          class com.example.einkaufsliste.ui.login.LoginViewModel {
              - resultMsg : MutableLiveData<String>
              + LoginViewModel()
              + getResultMsg()
              + login()
              + logout()
              + register()
          }
        }
      }

      namespace com.example.einkaufsliste {
          namespace ui.settings {
            class com.example.einkaufsliste.ui.settings.SettingsFragment {
                - ipAddress : EditText
                - save : Button
                + onCreateView()
            }
          }
        }


        namespace com.example.einkaufsliste {
          namespace ui.settings {
            class com.example.einkaufsliste.ui.settings.SettingsViewModel {
                - mText : MutableLiveData<String>
                + SettingsViewModel()
                + getText()
                + setIp()
            }
          }
        }


        com.example.einkaufsliste.ui.settings.SettingsFragment -up-|> androidx.fragment.app.Fragment
        com.example.einkaufsliste.ui.settings.SettingsFragment o-- com.example.einkaufsliste.ui.settings.SettingsViewModel : settingsViewModel
        com.example.einkaufsliste.ui.settings.SettingsViewModel -up-|> androidx.lifecycle.ViewModel

      com.example.einkaufsliste.ui.login.LoginFragment -up-|> androidx.fragment.app.Fragment
      com.example.einkaufsliste.ui.login.LoginFragment o-- com.example.einkaufsliste.ChangeFragmentInterface : changeFragmentInterface
      com.example.einkaufsliste.ui.login.LoginFragment o-- com.example.einkaufsliste.ui.login.LoginViewModel : loginViewModel
      com.example.einkaufsliste.ui.login.LoginViewModel -up-|> androidx.lifecycle.ViewModel


    com.example.einkaufsliste.ui.lists.BuyingListsAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
    com.example.einkaufsliste.ui.lists.BuyingListsAdapter o-- com.example.einkaufsliste.ChangeFragmentInterface : changeFragmentInterface
    com.example.einkaufsliste.ui.lists.BuyingListsAdapter o-- com.example.einkaufsliste.ui.lists.ListsViewModel : listsViewModel
    com.example.einkaufsliste.ui.lists.BuyingListsAdapter +-down- com.example.einkaufsliste.ui.lists.BuyingListsAdapter.BuyingListHolder
    com.example.einkaufsliste.ui.lists.BuyingListsAdapter.BuyingListHolder -up-|> androidx.recyclerview.widget.RecyclerView.ViewHolder
    com.example.einkaufsliste.ui.lists.ListDataAdapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
    com.example.einkaufsliste.ui.lists.ListDataAdapter +-down- com.example.einkaufsliste.ui.lists.ListDataAdapter.FirstViewHolder
    com.example.einkaufsliste.ui.lists.ListDataAdapter.FirstViewHolder -up-|> androidx.recyclerview.widget.RecyclerView.ViewHolder
    com.example.einkaufsliste.ui.lists.ListDataFragment -up-|> androidx.fragment.app.Fragment
    com.example.einkaufsliste.ui.lists.ListDataFragment o-- com.example.einkaufsliste.ui.lists.ListDataAdapter : adapter
    com.example.einkaufsliste.ui.lists.ListDataFragment o-- com.example.einkaufsliste.ui.lists.ListDataViewModel : listDataViewModel
    com.example.einkaufsliste.ui.lists.ListDataViewModel -up-|> androidx.lifecycle.ViewModel
    com.example.einkaufsliste.ui.lists.ListsFragment -up-|> androidx.fragment.app.Fragment
    com.example.einkaufsliste.ui.lists.ListsFragment o-- com.example.einkaufsliste.ui.lists.BuyingListsAdapter : adapter
    com.example.einkaufsliste.ui.lists.ListsFragment o-- com.example.einkaufsliste.ui.lists.ListsViewModel : listsViewModel
    com.example.einkaufsliste.ui.lists.ListsViewModel -up-|> androidx.lifecycle.ViewModel
    com.example.einkaufsliste.ui.lists.ListsViewModel o-- com.example.einkaufsliste.rest.InfrastructureWebservice : service

  
    com.example.einkaufsliste.models.Article .up.|> java.io.Serializable
  com.example.einkaufsliste.models.Article o-- com.example.einkaufsliste.models.BuyingList : buyingList
  com.example.einkaufsliste.models.BuyingList .up.|> java.io.Serializable
  com.example.einkaufsliste.models.Article o-- com.example.einkaufsliste.ui.lists.ListDataAdapter : adapter
  com.example.einkaufsliste.models.User .up.|> java.io.Serializable
  com.example.einkaufsliste.MainActivity .up.|> com.example.einkaufsliste.ChangeFragmentInterface
  com.example.einkaufsliste.MainActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.einkaufsliste.Repository o-- com.example.einkaufsliste.models.User : user


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
